name: Deploy to Neocities

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy to Neocities
  uses: bcomnes/deploy-to-neocities@v1
  with:
    api_token: ${{ secrets.NEOCITIES_API_TOKEN }}
    cleanup: false
    dist_dir: "."
    exclude: |
      **/.git*
      **/*.cur
