name: Deploy to Neocities

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install neocities

      - name: Deploy to Neocities
        run: node deploy.js
        env:
          NEOCITIES_USERNAME: ${{ secrets.NEOCITIES_USERNAME }}
          NEOCITIES_PASSWORD: ${{ secrets.NEOCITIES_PASSWORD }}
