name: Deploy to Neocities

on:
  push:
    branches:
      - main  # ou la branche que tu utilises

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Deploy to Neocities
        uses: bcomnes/deploy-to-neocities@v1
        with:
          apiKey: ${{ secrets.NEOCITIES_API_KEY }}
          dist_dir: .
          cleanup: true  # supprime les fichiers sur Neocities qui ne sont plus dans le repo

      - name: Deployment Summary
        run: |
          echo "------ Deployment Summary ------"
          FILE_COUNT=$(find . -type f -not -path "./.git/*" -not -path "./node_modules/*" | wc -l)
          TOTAL_SIZE=$(du -sh . | cut -f1)
          echo "Total files deployed: $FILE_COUNT"
          echo "Total size: $TOTAL_SIZE"
          echo "Files (top 20):"
          find . -type f -not -path "./.git/*" -not -path "./node_modules/*" | head -n 20
          echo "-------------------------------"
