name: Deploy to Neocities

on:
  push:
    branches:
      - main  # ou ta branche par défaut

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Neocities deploy tool
        run: npm install -g @bcomnes/deploy-to-neocities

      - name: Deploy files to Neocities
        env:
          NEOCITIES_API_KEY: ${{ secrets.NEOCITIES_API_KEY }}
        run: |
          SUCCESS=0
          FAIL=0
          while read file; do
            echo "Uploading $file..."
            if neocities deploy "$file"; then
              SUCCESS=$((SUCCESS+1))
            else
              echo "Failed: $file"
              FAIL=$((FAIL+1))
            fi
          done < <(find SP -type f -not -path "*/.git/*" -not -path "*/node_modules/*")

          echo "---------------------------------"
          echo "Deployment finished!"
          echo "Files uploaded successfully: $SUCCESS"
          echo "Files failed to upload: $FAIL"
          echo "---------------------------------"
