name: Deploy to Neocities

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to Neocities
        uses: bcomnes/deploy-to-neocities@v1
        with:
          api-key: ${{ secrets.NEOCITIES_API_KEY }}
          # Upload fichier par fichier
          files: |
            $(find . -type f -not -path "./.git/*" -not -path "./node_modules/*")
          # Ignore certains fichiers si besoin
          exclude: |
            .gitignore
            .github/**
        continue-on-error: true

      - name: Deployment summary
        run: |
          echo "------ Deployment Summary ------"
          echo "Total files in repo (excluding .git & node_modules):"
          find . -type f -not -path "./.git/*" -not -path "./node_modules/*" | w*_*
